services:
  app:
    build: .
    container_name: sla2-app
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=sla
      - DB_PASSWORD=sla1234
      - DB_NAME=sla2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ACTIVE_PROFILE=local
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: sla2-postgres
    environment:
      - POSTGRES_USER=sla
      - POSTGRES_PASSWORD=sla1234
      - POSTGRES_DB=sla2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: sla2-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: sla2-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 
