services:
  postgres:
    image: postgres:16-alpine
    container_name: sla2-postgres
    environment:
      - POSTGRES_USER=sla
      - POSTGRES_PASSWORD=sla1234
      - POSTGRES_DB=sla2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: sla2-redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: sla2-adminer
    environment:
      - ADMINER_DESIGN=pepa-linha
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 
