apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-grpc
  annotations:
    {{- with .Values.ingress.grpc.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.domain.api }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "chart.fullname" . }}
            port:
              number: {{ .Values.service.grpc.port }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.domain.api }}
    secretName: {{ .Values.ingress.domain.api }}-tls 