// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/v1/learning.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LearningService_GetCourseProgress_FullMethodName     = "/proto.v1.LearningService/GetCourseProgress"
	LearningService_GetSectionProgress_FullMethodName    = "/proto.v1.LearningService/GetSectionProgress"
	LearningService_UpdateUnitProgress_FullMethodName    = "/proto.v1.LearningService/UpdateUnitProgress"
	LearningService_GetMemoryStatus_FullMethodName       = "/proto.v1.LearningService/GetMemoryStatus"
	LearningService_UpdateMemoryStatus_FullMethodName    = "/proto.v1.LearningService/UpdateMemoryStatus"
	LearningService_ListMemoriesForReview_FullMethodName = "/proto.v1.LearningService/ListMemoriesForReview"
	LearningService_GetMemoryStats_FullMethodName        = "/proto.v1.LearningService/GetMemoryStats"
	LearningService_RecordLearningResult_FullMethodName  = "/proto.v1.LearningService/RecordLearningResult"
)

// LearningServiceClient is the client API for LearningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LearningService 提供学习进度相关的服务
type LearningServiceClient interface {
	// GetCourseProgress 获取课程学习进度
	GetCourseProgress(ctx context.Context, in *LearningServiceGetCourseProgressRequest, opts ...grpc.CallOption) (*LearningServiceGetCourseProgressResponse, error)
	// GetSectionProgress 获取章节学习进度
	GetSectionProgress(ctx context.Context, in *LearningServiceGetSectionProgressRequest, opts ...grpc.CallOption) (*LearningServiceGetSectionProgressResponse, error)
	// UpdateUnitProgress 更新单元学习进度
	UpdateUnitProgress(ctx context.Context, in *LearningServiceUpdateUnitProgressRequest, opts ...grpc.CallOption) (*LearningServiceUpdateUnitProgressResponse, error)
	// 获取记忆单元状态
	GetMemoryStatus(ctx context.Context, in *GetMemoryStatusRequest, opts ...grpc.CallOption) (*GetMemoryStatusResponse, error)
	// 更新记忆单元状态
	UpdateMemoryStatus(ctx context.Context, in *UpdateMemoryStatusRequest, opts ...grpc.CallOption) (*UpdateMemoryStatusResponse, error)
	// 获取需要复习的记忆单元列表
	ListMemoriesForReview(ctx context.Context, in *ListMemoriesForReviewRequest, opts ...grpc.CallOption) (*ListMemoriesForReviewResponse, error)
	// 获取记忆单元学习统计
	GetMemoryStats(ctx context.Context, in *GetMemoryStatsRequest, opts ...grpc.CallOption) (*GetMemoryStatsResponse, error)
	// 记录学习结果
	RecordLearningResult(ctx context.Context, in *RecordLearningResultRequest, opts ...grpc.CallOption) (*RecordLearningResultResponse, error)
}

type learningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLearningServiceClient(cc grpc.ClientConnInterface) LearningServiceClient {
	return &learningServiceClient{cc}
}

func (c *learningServiceClient) GetCourseProgress(ctx context.Context, in *LearningServiceGetCourseProgressRequest, opts ...grpc.CallOption) (*LearningServiceGetCourseProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LearningServiceGetCourseProgressResponse)
	err := c.cc.Invoke(ctx, LearningService_GetCourseProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) GetSectionProgress(ctx context.Context, in *LearningServiceGetSectionProgressRequest, opts ...grpc.CallOption) (*LearningServiceGetSectionProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LearningServiceGetSectionProgressResponse)
	err := c.cc.Invoke(ctx, LearningService_GetSectionProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) UpdateUnitProgress(ctx context.Context, in *LearningServiceUpdateUnitProgressRequest, opts ...grpc.CallOption) (*LearningServiceUpdateUnitProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LearningServiceUpdateUnitProgressResponse)
	err := c.cc.Invoke(ctx, LearningService_UpdateUnitProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) GetMemoryStatus(ctx context.Context, in *GetMemoryStatusRequest, opts ...grpc.CallOption) (*GetMemoryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemoryStatusResponse)
	err := c.cc.Invoke(ctx, LearningService_GetMemoryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) UpdateMemoryStatus(ctx context.Context, in *UpdateMemoryStatusRequest, opts ...grpc.CallOption) (*UpdateMemoryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMemoryStatusResponse)
	err := c.cc.Invoke(ctx, LearningService_UpdateMemoryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) ListMemoriesForReview(ctx context.Context, in *ListMemoriesForReviewRequest, opts ...grpc.CallOption) (*ListMemoriesForReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemoriesForReviewResponse)
	err := c.cc.Invoke(ctx, LearningService_ListMemoriesForReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) GetMemoryStats(ctx context.Context, in *GetMemoryStatsRequest, opts ...grpc.CallOption) (*GetMemoryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemoryStatsResponse)
	err := c.cc.Invoke(ctx, LearningService_GetMemoryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *learningServiceClient) RecordLearningResult(ctx context.Context, in *RecordLearningResultRequest, opts ...grpc.CallOption) (*RecordLearningResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordLearningResultResponse)
	err := c.cc.Invoke(ctx, LearningService_RecordLearningResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LearningServiceServer is the server API for LearningService service.
// All implementations must embed UnimplementedLearningServiceServer
// for forward compatibility.
//
// LearningService 提供学习进度相关的服务
type LearningServiceServer interface {
	// GetCourseProgress 获取课程学习进度
	GetCourseProgress(context.Context, *LearningServiceGetCourseProgressRequest) (*LearningServiceGetCourseProgressResponse, error)
	// GetSectionProgress 获取章节学习进度
	GetSectionProgress(context.Context, *LearningServiceGetSectionProgressRequest) (*LearningServiceGetSectionProgressResponse, error)
	// UpdateUnitProgress 更新单元学习进度
	UpdateUnitProgress(context.Context, *LearningServiceUpdateUnitProgressRequest) (*LearningServiceUpdateUnitProgressResponse, error)
	// 获取记忆单元状态
	GetMemoryStatus(context.Context, *GetMemoryStatusRequest) (*GetMemoryStatusResponse, error)
	// 更新记忆单元状态
	UpdateMemoryStatus(context.Context, *UpdateMemoryStatusRequest) (*UpdateMemoryStatusResponse, error)
	// 获取需要复习的记忆单元列表
	ListMemoriesForReview(context.Context, *ListMemoriesForReviewRequest) (*ListMemoriesForReviewResponse, error)
	// 获取记忆单元学习统计
	GetMemoryStats(context.Context, *GetMemoryStatsRequest) (*GetMemoryStatsResponse, error)
	// 记录学习结果
	RecordLearningResult(context.Context, *RecordLearningResultRequest) (*RecordLearningResultResponse, error)
	mustEmbedUnimplementedLearningServiceServer()
}

// UnimplementedLearningServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLearningServiceServer struct{}

func (UnimplementedLearningServiceServer) GetCourseProgress(context.Context, *LearningServiceGetCourseProgressRequest) (*LearningServiceGetCourseProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseProgress not implemented")
}
func (UnimplementedLearningServiceServer) GetSectionProgress(context.Context, *LearningServiceGetSectionProgressRequest) (*LearningServiceGetSectionProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSectionProgress not implemented")
}
func (UnimplementedLearningServiceServer) UpdateUnitProgress(context.Context, *LearningServiceUpdateUnitProgressRequest) (*LearningServiceUpdateUnitProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUnitProgress not implemented")
}
func (UnimplementedLearningServiceServer) GetMemoryStatus(context.Context, *GetMemoryStatusRequest) (*GetMemoryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemoryStatus not implemented")
}
func (UnimplementedLearningServiceServer) UpdateMemoryStatus(context.Context, *UpdateMemoryStatusRequest) (*UpdateMemoryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMemoryStatus not implemented")
}
func (UnimplementedLearningServiceServer) ListMemoriesForReview(context.Context, *ListMemoriesForReviewRequest) (*ListMemoriesForReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMemoriesForReview not implemented")
}
func (UnimplementedLearningServiceServer) GetMemoryStats(context.Context, *GetMemoryStatsRequest) (*GetMemoryStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemoryStats not implemented")
}
func (UnimplementedLearningServiceServer) RecordLearningResult(context.Context, *RecordLearningResultRequest) (*RecordLearningResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordLearningResult not implemented")
}
func (UnimplementedLearningServiceServer) mustEmbedUnimplementedLearningServiceServer() {}
func (UnimplementedLearningServiceServer) testEmbeddedByValue()                         {}

// UnsafeLearningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LearningServiceServer will
// result in compilation errors.
type UnsafeLearningServiceServer interface {
	mustEmbedUnimplementedLearningServiceServer()
}

func RegisterLearningServiceServer(s grpc.ServiceRegistrar, srv LearningServiceServer) {
	// If the following call pancis, it indicates UnimplementedLearningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LearningService_ServiceDesc, srv)
}

func _LearningService_GetCourseProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LearningServiceGetCourseProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).GetCourseProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_GetCourseProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).GetCourseProgress(ctx, req.(*LearningServiceGetCourseProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_GetSectionProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LearningServiceGetSectionProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).GetSectionProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_GetSectionProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).GetSectionProgress(ctx, req.(*LearningServiceGetSectionProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_UpdateUnitProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LearningServiceUpdateUnitProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).UpdateUnitProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_UpdateUnitProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).UpdateUnitProgress(ctx, req.(*LearningServiceUpdateUnitProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_GetMemoryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).GetMemoryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_GetMemoryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).GetMemoryStatus(ctx, req.(*GetMemoryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_UpdateMemoryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemoryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).UpdateMemoryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_UpdateMemoryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).UpdateMemoryStatus(ctx, req.(*UpdateMemoryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_ListMemoriesForReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemoriesForReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).ListMemoriesForReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_ListMemoriesForReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).ListMemoriesForReview(ctx, req.(*ListMemoriesForReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_GetMemoryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).GetMemoryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_GetMemoryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).GetMemoryStats(ctx, req.(*GetMemoryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LearningService_RecordLearningResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordLearningResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LearningServiceServer).RecordLearningResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LearningService_RecordLearningResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LearningServiceServer).RecordLearningResult(ctx, req.(*RecordLearningResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LearningService_ServiceDesc is the grpc.ServiceDesc for LearningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LearningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.LearningService",
	HandlerType: (*LearningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCourseProgress",
			Handler:    _LearningService_GetCourseProgress_Handler,
		},
		{
			MethodName: "GetSectionProgress",
			Handler:    _LearningService_GetSectionProgress_Handler,
		},
		{
			MethodName: "UpdateUnitProgress",
			Handler:    _LearningService_UpdateUnitProgress_Handler,
		},
		{
			MethodName: "GetMemoryStatus",
			Handler:    _LearningService_GetMemoryStatus_Handler,
		},
		{
			MethodName: "UpdateMemoryStatus",
			Handler:    _LearningService_UpdateMemoryStatus_Handler,
		},
		{
			MethodName: "ListMemoriesForReview",
			Handler:    _LearningService_ListMemoriesForReview_Handler,
		},
		{
			MethodName: "GetMemoryStats",
			Handler:    _LearningService_GetMemoryStats_Handler,
		},
		{
			MethodName: "RecordLearningResult",
			Handler:    _LearningService_RecordLearningResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/learning.proto",
}
