// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: proto/v1/question.proto

// ============= 基础定义 =============

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuestionService_Get_FullMethodName     = "/proto.v1.QuestionService/Get"
	QuestionService_Create_FullMethodName  = "/proto.v1.QuestionService/Create"
	QuestionService_Search_FullMethodName  = "/proto.v1.QuestionService/Search"
	QuestionService_Update_FullMethodName  = "/proto.v1.QuestionService/Update"
	QuestionService_Delete_FullMethodName  = "/proto.v1.QuestionService/Delete"
	QuestionService_Publish_FullMethodName = "/proto.v1.QuestionService/Publish"
)

// QuestionServiceClient is the client API for QuestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QuestionService 题目服务
type QuestionServiceClient interface {
	Get(ctx context.Context, in *QuestionServiceGetRequest, opts ...grpc.CallOption) (*QuestionServiceGetResponse, error)
	Create(ctx context.Context, in *QuestionServiceCreateRequest, opts ...grpc.CallOption) (*QuestionServiceCreateResponse, error)
	Search(ctx context.Context, in *QuestionServiceSearchRequest, opts ...grpc.CallOption) (*QuestionServiceSearchResponse, error)
	Update(ctx context.Context, in *QuestionServiceUpdateRequest, opts ...grpc.CallOption) (*QuestionServiceUpdateResponse, error)
	Delete(ctx context.Context, in *QuestionServiceDeleteRequest, opts ...grpc.CallOption) (*QuestionServiceDeleteResponse, error)
	Publish(ctx context.Context, in *QuestionServicePublishRequest, opts ...grpc.CallOption) (*QuestionServicePublishResponse, error)
}

type questionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestionServiceClient(cc grpc.ClientConnInterface) QuestionServiceClient {
	return &questionServiceClient{cc}
}

func (c *questionServiceClient) Get(ctx context.Context, in *QuestionServiceGetRequest, opts ...grpc.CallOption) (*QuestionServiceGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionServiceGetResponse)
	err := c.cc.Invoke(ctx, QuestionService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiceClient) Create(ctx context.Context, in *QuestionServiceCreateRequest, opts ...grpc.CallOption) (*QuestionServiceCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionServiceCreateResponse)
	err := c.cc.Invoke(ctx, QuestionService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiceClient) Search(ctx context.Context, in *QuestionServiceSearchRequest, opts ...grpc.CallOption) (*QuestionServiceSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionServiceSearchResponse)
	err := c.cc.Invoke(ctx, QuestionService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiceClient) Update(ctx context.Context, in *QuestionServiceUpdateRequest, opts ...grpc.CallOption) (*QuestionServiceUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionServiceUpdateResponse)
	err := c.cc.Invoke(ctx, QuestionService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiceClient) Delete(ctx context.Context, in *QuestionServiceDeleteRequest, opts ...grpc.CallOption) (*QuestionServiceDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionServiceDeleteResponse)
	err := c.cc.Invoke(ctx, QuestionService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questionServiceClient) Publish(ctx context.Context, in *QuestionServicePublishRequest, opts ...grpc.CallOption) (*QuestionServicePublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuestionServicePublishResponse)
	err := c.cc.Invoke(ctx, QuestionService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestionServiceServer is the server API for QuestionService service.
// All implementations must embed UnimplementedQuestionServiceServer
// for forward compatibility.
//
// QuestionService 题目服务
type QuestionServiceServer interface {
	Get(context.Context, *QuestionServiceGetRequest) (*QuestionServiceGetResponse, error)
	Create(context.Context, *QuestionServiceCreateRequest) (*QuestionServiceCreateResponse, error)
	Search(context.Context, *QuestionServiceSearchRequest) (*QuestionServiceSearchResponse, error)
	Update(context.Context, *QuestionServiceUpdateRequest) (*QuestionServiceUpdateResponse, error)
	Delete(context.Context, *QuestionServiceDeleteRequest) (*QuestionServiceDeleteResponse, error)
	Publish(context.Context, *QuestionServicePublishRequest) (*QuestionServicePublishResponse, error)
	mustEmbedUnimplementedQuestionServiceServer()
}

// UnimplementedQuestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuestionServiceServer struct{}

func (UnimplementedQuestionServiceServer) Get(context.Context, *QuestionServiceGetRequest) (*QuestionServiceGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedQuestionServiceServer) Create(context.Context, *QuestionServiceCreateRequest) (*QuestionServiceCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedQuestionServiceServer) Search(context.Context, *QuestionServiceSearchRequest) (*QuestionServiceSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedQuestionServiceServer) Update(context.Context, *QuestionServiceUpdateRequest) (*QuestionServiceUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedQuestionServiceServer) Delete(context.Context, *QuestionServiceDeleteRequest) (*QuestionServiceDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedQuestionServiceServer) Publish(context.Context, *QuestionServicePublishRequest) (*QuestionServicePublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedQuestionServiceServer) mustEmbedUnimplementedQuestionServiceServer() {}
func (UnimplementedQuestionServiceServer) testEmbeddedByValue()                         {}

// UnsafeQuestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestionServiceServer will
// result in compilation errors.
type UnsafeQuestionServiceServer interface {
	mustEmbedUnimplementedQuestionServiceServer()
}

func RegisterQuestionServiceServer(s grpc.ServiceRegistrar, srv QuestionServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuestionService_ServiceDesc, srv)
}

func _QuestionService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionServiceGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).Get(ctx, req.(*QuestionServiceGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionServiceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).Create(ctx, req.(*QuestionServiceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionServiceSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).Search(ctx, req.(*QuestionServiceSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionServiceUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).Update(ctx, req.(*QuestionServiceUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionServiceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).Delete(ctx, req.(*QuestionServiceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestionService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuestionServicePublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestionServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestionService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestionServiceServer).Publish(ctx, req.(*QuestionServicePublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuestionService_ServiceDesc is the grpc.ServiceDesc for QuestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.QuestionService",
	HandlerType: (*QuestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _QuestionService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _QuestionService_Create_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _QuestionService_Search_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _QuestionService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _QuestionService_Delete_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _QuestionService_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/question.proto",
}
