server:
  port: "9000"
  mode: "debug"
  version: "v1.0.0"

grpc:
  port: 9001

database:
  host: localhost
  port: 5432
  user: sla
  password: sla1234
  dbname: sla2
  sslmode: disable
  debug: true
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "30m"
  conn_max_idle_time: "10m"

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  min_retry_backoff: "100ms"
  max_retry_backoff: "2s"
  pool_size: 100
  min_idle_conns: 10
  max_conn_age: "30m"

log:
  level: "debug"
  file_path: "./logs/app.log"

jwt:
  token_secret_key: "dj2n8xK9pL5mQ7vR3fT1hG4wY6sB8cA0eU9nM2iP"
  refresh_secret_key: "kL9mN5vX7pH2jR4wT8cA3fE6bY1iU0qS5nD8mK2p"

apple:
  client_id: "your-apple-client-id-here"
