# 本地环境特定配置
database:
  host: localhost
  port: 5432
  user: sla
  password: sla1234
  dbname: sla2

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  token_secret_key: "dj2n8xK9pL5mQ7vR3fT1hG4wY6sB8cA0eU9nM2iP"
  refresh_secret_key: "kL9mN5vX7pH2jR4wT8cA3fE6bY1iU0qS5nD8mK2p"
  token_expiration: 168
  refresh_expiration: 720
