# 生产环境特定配置
database:
  host: "postgres-postgresql.default.svc.cluster.local"
  port: "5432"
  user: "sla"
  password: "sla1234"
  dbname: "sla2"

redis:
  host: "redis-master.default.svc.cluster.local"
  port: "6379"
  password: ""
  db: 0

jwt:
  token_secret_key: "mX4nJ8pK2cL7vR9wT5hB3fA6yU1iE8qD0sN4mK9p"
  refresh_secret_key: "bH7kL2mN9vX4pH6jR8wT1cA5fE3yU7iQ2sD8nK4p"
  token_expiration: 168
  refresh_expiration: 720
