server:
  port: "9000"
  mode: "debug"
  version: "v1.0.0"

database:
  host: "localhost"
  port: "5432"
  user: "sla"
  password: "sla1234"
  dbname: "sla2"
  debug: false
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "30m"
  conn_max_idle_time: "10m"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0
  max_retries: 3
  min_retry_backoff: "100ms"
  max_retry_backoff: "2s"
  pool_size: 100
  min_idle_conns: 10
  max_conn_age: "30m"

log:
  level: "info"

jwt:
  secret_key: "dj2m#9K$pL7&vX4@nR5*wQ8^hF3!tY6"
